"""Evidence record shape, canonical serialization, replay comparability and rendering."""

from attestql.evidence.build import ExecutionIdentity, IncompleteEvidence, build_evidence_record
from attestql.evidence.load import (
    LoadedRecord,
    Recomputed,
    UnreadableRecord,
    load_descriptor,
    load_record,
    load_result,
    load_row,
    load_value,
)
from attestql.evidence.record import EvidenceRecord, ValidationOutcome
from attestql.evidence.render import (
    RowDifference,
    RowGroup,
    record_json,
    result_digest,
    result_json,
    row_difference,
    row_difference_json,
    statement_source_json,
    write_json,
)
from attestql.evidence.replay import (
    PRECONDITION_FIELDS,
    RULE_FIELDS,
    SESSION_PRECONDITIONS,
    ComparabilityResult,
    ComparabilityVerdict,
    compare_r_ord,
    compare_r_set,
    precondition_mismatches,
    preconditions_match,
)
from attestql.evidence.serialize import (
    SerializationDescriptor,
    UnsupportedValue,
    canonical_serialize,
    canonical_type_tag,
    typed_row,
    typed_value,
)
from attestql.evidence.types import (
    ENGINE_POSTGRESQL,
    ENGINE_SQLITE,
    ENGINES,
    FixtureDigest,
    QuestionMetadata,
    ReplayRule,
    SessionSettings,
    SortKey,
    StatementSource,
)

__all__ = [
    "ENGINES",
    "ENGINE_POSTGRESQL",
    "ENGINE_SQLITE",
    "PRECONDITION_FIELDS",
    "RULE_FIELDS",
    "SESSION_PRECONDITIONS",
    "ComparabilityResult",
    "ComparabilityVerdict",
    "EvidenceRecord",
    "ExecutionIdentity",
    "FixtureDigest",
    "IncompleteEvidence",
    "LoadedRecord",
    "QuestionMetadata",
    "Recomputed",
    "ReplayRule",
    "RowDifference",
    "RowGroup",
    "SerializationDescriptor",
    "SessionSettings",
    "SortKey",
    "StatementSource",
    "UnreadableRecord",
    "UnsupportedValue",
    "ValidationOutcome",
    "build_evidence_record",
    "canonical_serialize",
    "canonical_type_tag",
    "compare_r_ord",
    "compare_r_set",
    "load_descriptor",
    "load_record",
    "load_result",
    "load_row",
    "load_value",
    "precondition_mismatches",
    "preconditions_match",
    "record_json",
    "result_digest",
    "result_json",
    "row_difference",
    "row_difference_json",
    "statement_source_json",
    "typed_row",
    "typed_value",
    "write_json",
]
